//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SealSignSQSClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SealSignSQSClient {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SealSignSQSClient() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SealSignSQSClient.SealSignSQSClient", typeof(SealSignSQSClient).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the new owner user account for the selected documents:.
        /// </summary>
        internal static string ChangeOwnerText {
            get {
                return ResourceManager.GetString("ChangeOwnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SealSignSQSClient - Change Owner.
        /// </summary>
        internal static string ChangeOwnerTitle {
            get {
                return ResourceManager.GetString("ChangeOwnerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature device not connected..
        /// </summary>
        internal static string DeviceNotConnected {
            get {
                return ResourceManager.GetString("DeviceNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has ocurred. Error Description: .
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting information . . ..
        /// </summary>
        internal static string GettingJobInfo {
            get {
                return ResourceManager.GetString("GettingJobInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing device . . ..
        /// </summary>
        internal static string InitializingDevice {
            get {
                return ResourceManager.GetString("InitializingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} new pending documents..
        /// </summary>
        internal static string NewPendingDocs {
            get {
                return ResourceManager.GetString("NewPendingDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner: {0}.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password can not be empty..
        /// </summary>
        internal static string PasswordMandatory {
            get {
                return ResourceManager.GetString("PasswordMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  pending documents. .
        /// </summary>
        internal static string PendingDocs {
            get {
                return ResourceManager.GetString("PendingDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing list . . ..
        /// </summary>
        internal static string RefreshingList {
            get {
                return ResourceManager.GetString("RefreshingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove document from pending job list?.
        /// </summary>
        internal static string RemovePendingJob {
            get {
                return ResourceManager.GetString("RemovePendingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected documents?.
        /// </summary>
        internal static string RemoveSelectedJobs {
            get {
                return ResourceManager.GetString("RemoveSelectedJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove document from signed job list?.
        /// </summary>
        internal static string RemoveSignedJob {
            get {
                return ResourceManager.GetString("RemoveSignedJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing documents . . ..
        /// </summary>
        internal static string RemovingJobs {
            get {
                return ResourceManager.GetString("RemovingJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service url can not be empty..
        /// </summary>
        internal static string ServiceUrlMandatory {
            get {
                return ResourceManager.GetString("ServiceUrlMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Success.
        /// </summary>
        internal static string SignatureSuccess {
            get {
                return ResourceManager.GetString("SignatureSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  signed documents. .
        /// </summary>
        internal static string SignedDocs {
            get {
                return ResourceManager.GetString("SignedDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing document . . ..
        /// </summary>
        internal static string Signing {
            get {
                return ResourceManager.GetString("Signing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing time: {0} {1}.
        /// </summary>
        internal static string SigningTime {
            get {
                return ResourceManager.GetString("SigningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source computer: {0}.
        /// </summary>
        internal static string SourceComputer {
            get {
                return ResourceManager.GetString("SourceComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission time: {0} {1}.
        /// </summary>
        internal static string SubmissionTime {
            get {
                return ResourceManager.GetString("SubmissionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SealSignSQSClient - Signature Jobs.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name can not be empty..
        /// </summary>
        internal static string UsernameMandatory {
            get {
                return ResourceManager.GetString("UsernameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for signature . . ..
        /// </summary>
        internal static string WaitingForSignature {
            get {
                return ResourceManager.GetString("WaitingForSignature", resourceCulture);
            }
        }
    }
}
