//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SealSignSQSService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueReference", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSTypes")]
    public partial class QueueReference : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        private string nameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobReference", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSTypes")]
    public partial class JobReference : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string JobMetadataField;
        
        private string computerNameField;
        
        private int idField;
        
        private int idQueueField;
        
        private string jobTitleField;
        
        private int originalJobIdField;
        
        private string ownerField;
        
        private string queueNameField;
        
        private System.DateTime timeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobMetadata
        {
            get
            {
                return this.JobMetadataField;
            }
            set
            {
                this.JobMetadataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string computerName
        {
            get
            {
                return this.computerNameField;
            }
            set
            {
                this.computerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idQueue
        {
            get
            {
                return this.idQueueField;
            }
            set
            {
                this.idQueueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobTitle
        {
            get
            {
                return this.jobTitleField;
            }
            set
            {
                this.jobTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int originalJobId
        {
            get
            {
                return this.originalJobIdField;
            }
            set
            {
                this.originalJobIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string queueName
        {
            get
            {
                return this.queueNameField;
            }
            set
            {
                this.queueNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Job", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSTypes")]
    public partial class Job : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SealSignSQSService.JobReferenceEx jobReferenceExField;
        
        private SealSignSQSService.SignatureClientBehaviour[] signatureClientBehaviourField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SealSignSQSService.JobReferenceEx jobReferenceEx
        {
            get
            {
                return this.jobReferenceExField;
            }
            set
            {
                this.jobReferenceExField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SealSignSQSService.SignatureClientBehaviour[] signatureClientBehaviour
        {
            get
            {
                return this.signatureClientBehaviourField;
            }
            set
            {
                this.signatureClientBehaviourField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobReferenceEx", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSTypes")]
    public partial class JobReferenceEx : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string JobMetadataField;
        
        private byte[] blobField;
        
        private string computerNameField;
        
        private int idField;
        
        private int idQueueField;
        
        private string jobTitleField;
        
        private int originalJobIdField;
        
        private string ownerField;
        
        private bool processedField;
        
        private string queueNameField;
        
        private System.DateTime timeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobMetadata
        {
            get
            {
                return this.JobMetadataField;
            }
            set
            {
                this.JobMetadataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] blob
        {
            get
            {
                return this.blobField;
            }
            set
            {
                this.blobField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string computerName
        {
            get
            {
                return this.computerNameField;
            }
            set
            {
                this.computerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idQueue
        {
            get
            {
                return this.idQueueField;
            }
            set
            {
                this.idQueueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobTitle
        {
            get
            {
                return this.jobTitleField;
            }
            set
            {
                this.jobTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int originalJobId
        {
            get
            {
                return this.originalJobIdField;
            }
            set
            {
                this.originalJobIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool processed
        {
            get
            {
                return this.processedField;
            }
            set
            {
                this.processedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string queueName
        {
            get
            {
                return this.queueNameField;
            }
            set
            {
                this.queueNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureClientBehaviour", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSTypes")]
    public partial class SignatureClientBehaviour : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string providerParameterField;
        
        private string signatureAccountField;
        
        private string signatureIdField;
        
        private string signatureWindowTitleField;
        
        private SealSignSQSService.STUConfiguration stuConfigurationField;
        
        private string uriField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string providerParameter
        {
            get
            {
                return this.providerParameterField;
            }
            set
            {
                this.providerParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signatureAccount
        {
            get
            {
                return this.signatureAccountField;
            }
            set
            {
                this.signatureAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signatureId
        {
            get
            {
                return this.signatureIdField;
            }
            set
            {
                this.signatureIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signatureWindowTitle
        {
            get
            {
                return this.signatureWindowTitleField;
            }
            set
            {
                this.signatureWindowTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SealSignSQSService.STUConfiguration stuConfiguration
        {
            get
            {
                return this.stuConfigurationField;
            }
            set
            {
                this.stuConfigurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uri
        {
            get
            {
                return this.uriField;
            }
            set
            {
                this.uriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STUConfiguration", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSTypes")]
    public partial class STUConfiguration : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SealSignSQSService.STUButtonDefinition CancelButtonField;
        
        private byte[] ImageField;
        
        private SealSignSQSService.STUButtonDefinition OKButtonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SealSignSQSService.STUButtonDefinition CancelButton
        {
            get
            {
                return this.CancelButtonField;
            }
            set
            {
                this.CancelButtonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SealSignSQSService.STUButtonDefinition OKButton
        {
            get
            {
                return this.OKButtonField;
            }
            set
            {
                this.OKButtonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STUButtonDefinition", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSTypes")]
    public partial class STUButtonDefinition : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int x1Field;
        
        private int x2Field;
        
        private int y1Field;
        
        private int y2Field;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x1
        {
            get
            {
                return this.x1Field;
            }
            set
            {
                this.x1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x2
        {
            get
            {
                return this.x2Field;
            }
            set
            {
                this.x2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y1
        {
            get
            {
                return this.y1Field;
            }
            set
            {
                this.y1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y2
        {
            get
            {
                return this.y2Field;
            }
            set
            {
                this.y2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BiometricSignatureContext", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
    public partial class BiometricSignatureContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] biometricStateField;
        
        private System.Guid instanceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] biometricState
        {
            get
            {
                return this.biometricStateField;
            }
            set
            {
                this.biometricStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid instance
        {
            get
            {
                return this.instanceField;
            }
            set
            {
                this.instanceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfflineBiometricSignature", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
    public partial class OfflineBiometricSignature : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string biometricAccountField;
        
        private string biometricIdField;
        
        private System.Guid instanceField;
        
        private byte[] offlineBiometricStateField;
        
        private string providerParameterField;
        
        private int signatureIndexField;
        
        private string uriField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string biometricAccount
        {
            get
            {
                return this.biometricAccountField;
            }
            set
            {
                this.biometricAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string biometricId
        {
            get
            {
                return this.biometricIdField;
            }
            set
            {
                this.biometricIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid instance
        {
            get
            {
                return this.instanceField;
            }
            set
            {
                this.instanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] offlineBiometricState
        {
            get
            {
                return this.offlineBiometricStateField;
            }
            set
            {
                this.offlineBiometricStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string providerParameter
        {
            get
            {
                return this.providerParameterField;
            }
            set
            {
                this.providerParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int signatureIndex
        {
            get
            {
                return this.signatureIndexField;
            }
            set
            {
                this.signatureIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uri
        {
            get
            {
                return this.uriField;
            }
            set
            {
                this.uriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
    public partial class SealSignDSSFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private uint errorCodeField;
        
        private string messageField;
        
        private string stackTraceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SealSignSQSService.ISignatureQueueService")]
    public interface ISignatureQueueService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/AddQueue", ReplyAction="http://tempuri.org/ISignatureQueueService/AddQueueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/AddQueueSealSignDSSFaultContractFault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        int AddQueue(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/RemoveQueue", ReplyAction="http://tempuri.org/ISignatureQueueService/RemoveQueueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/RemoveQueueSealSignDSSFaultContractFaul" +
            "t", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        void RemoveQueue(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/GetQueueReferences", ReplyAction="http://tempuri.org/ISignatureQueueService/GetQueueReferencesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/GetQueueReferencesSealSignDSSFaultContr" +
            "actFault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        SealSignSQSService.QueueReference[] GetQueueReferences();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/AddJobFromSpooler", ReplyAction="http://tempuri.org/ISignatureQueueService/AddJobFromSpoolerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/AddJobFromSpoolerSealSignDSSFaultContra" +
            "ctFault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        int AddJobFromSpooler(string queueName, string owner, string computerName, int originalJobId, string jobTitle, byte[] blob, string jobMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/AddJob", ReplyAction="http://tempuri.org/ISignatureQueueService/AddJobResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/AddJobSealSignDSSFaultContractFault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        int AddJob(string queueName, int originalJobId, string jobTitle, byte[] blob, string jobMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/SetProcessedJob", ReplyAction="http://tempuri.org/ISignatureQueueService/SetProcessedJobResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/SetProcessedJobSealSignDSSFaultContract" +
            "Fault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        void SetProcessedJob(int id, byte[] document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/RemoveJob", ReplyAction="http://tempuri.org/ISignatureQueueService/RemoveJobResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/RemoveJobSealSignDSSFaultContractFault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        void RemoveJob(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/ChangeJobOwner", ReplyAction="http://tempuri.org/ISignatureQueueService/ChangeJobOwnerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/ChangeJobOwnerSealSignDSSFaultContractF" +
            "ault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        void ChangeJobOwner(int id, string newOwner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/GetPendingJobs", ReplyAction="http://tempuri.org/ISignatureQueueService/GetPendingJobsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/GetPendingJobsSealSignDSSFaultContractF" +
            "ault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        SealSignSQSService.JobReference[] GetPendingJobs(SealSignSQSService.QueueReference[] queueReferences, string owner, string computerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/GetProcessedJobs", ReplyAction="http://tempuri.org/ISignatureQueueService/GetProcessedJobsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/GetProcessedJobsSealSignDSSFaultContrac" +
            "tFault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        SealSignSQSService.JobReference[] GetProcessedJobs(SealSignSQSService.QueueReference[] queueReferences, string owner, string computerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/GetJob", ReplyAction="http://tempuri.org/ISignatureQueueService/GetJobResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/GetJobSealSignDSSFaultContractFault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        SealSignSQSService.Job GetJob(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/BeginBiometricSignatureProvider", ReplyAction="http://tempuri.org/ISignatureQueueService/BeginBiometricSignatureProviderResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/BeginBiometricSignatureProviderSealSign" +
            "DSSFaultContractFault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        SealSignSQSService.BiometricSignatureContext BeginBiometricSignatureProvider(int idDocument, int signatureIndex, string queueName, string biometricId, string biometricAccount, string uri, string providerParameter, byte[] document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/EndBiometricSignatureProvider", ReplyAction="http://tempuri.org/ISignatureQueueService/EndBiometricSignatureProviderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/EndBiometricSignatureProviderSealSignDS" +
            "SFaultContractFault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="signedDocument")]
        byte[] EndBiometricSignatureProvider(System.Guid instance, byte[] biometricState, int idDocument, int signatureIndex, string queueName, string uri, string providerParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/SyncOfflineSignature", ReplyAction="http://tempuri.org/ISignatureQueueService/SyncOfflineSignatureResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/SyncOfflineSignatureSealSignDSSFaultCon" +
            "tractFault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        void SyncOfflineSignature(int idDocument, int signatureIndex, string queueName, string biometricId, string biometricAccount, string uri, string providerParameter, byte[] document, System.Guid instance, byte[] offlineBiometricState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/SyncOfflineSignatureToArray", ReplyAction="http://tempuri.org/ISignatureQueueService/SyncOfflineSignatureToArrayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/SyncOfflineSignatureToArraySealSignDSSF" +
            "aultContractFault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="signedDocument")]
        byte[] SyncOfflineSignatureToArray(int idDocument, int signatureIndex, string queueName, string biometricId, string biometricAccount, string uri, string providerParameter, byte[] document, System.Guid instance, byte[] offlineBiometricState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/SyncOfflineSignatures", ReplyAction="http://tempuri.org/ISignatureQueueService/SyncOfflineSignaturesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/SyncOfflineSignaturesSealSignDSSFaultCo" +
            "ntractFault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        void SyncOfflineSignatures(int idDocument, string queueName, SealSignSQSService.OfflineBiometricSignature[] offlineSignatures, byte[] document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignatureQueueService/SyncOfflineSignaturesToArray", ReplyAction="http://tempuri.org/ISignatureQueueService/SyncOfflineSignaturesToArrayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealSignSQSService.SealSignDSSFaultContract), Action="http://tempuri.org/ISignatureQueueService/SyncOfflineSignaturesToArraySealSignDSS" +
            "FaultContractFault", Name="SealSignDSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/SealSignSQSService")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="signedDocument")]
        byte[] SyncOfflineSignaturesToArray(int idDocument, string queueName, SealSignSQSService.OfflineBiometricSignature[] offlineSignatures, byte[] document);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISignatureQueueServiceChannel : SealSignSQSService.ISignatureQueueService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SignatureQueueServiceClient : System.ServiceModel.ClientBase<SealSignSQSService.ISignatureQueueService>, SealSignSQSService.ISignatureQueueService
    {
        
        public SignatureQueueServiceClient()
        {
        }
        
        public SignatureQueueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SignatureQueueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SignatureQueueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SignatureQueueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int AddQueue(string name)
        {
            return base.Channel.AddQueue(name);
        }
        
        public void RemoveQueue(int id)
        {
            base.Channel.RemoveQueue(id);
        }
        
        public SealSignSQSService.QueueReference[] GetQueueReferences()
        {
            return base.Channel.GetQueueReferences();
        }
        
        public int AddJobFromSpooler(string queueName, string owner, string computerName, int originalJobId, string jobTitle, byte[] blob, string jobMetadata)
        {
            return base.Channel.AddJobFromSpooler(queueName, owner, computerName, originalJobId, jobTitle, blob, jobMetadata);
        }
        
        public int AddJob(string queueName, int originalJobId, string jobTitle, byte[] blob, string jobMetadata)
        {
            return base.Channel.AddJob(queueName, originalJobId, jobTitle, blob, jobMetadata);
        }
        
        public void SetProcessedJob(int id, byte[] document)
        {
            base.Channel.SetProcessedJob(id, document);
        }
        
        public void RemoveJob(int id)
        {
            base.Channel.RemoveJob(id);
        }
        
        public void ChangeJobOwner(int id, string newOwner)
        {
            base.Channel.ChangeJobOwner(id, newOwner);
        }
        
        public SealSignSQSService.JobReference[] GetPendingJobs(SealSignSQSService.QueueReference[] queueReferences, string owner, string computerName)
        {
            return base.Channel.GetPendingJobs(queueReferences, owner, computerName);
        }
        
        public SealSignSQSService.JobReference[] GetProcessedJobs(SealSignSQSService.QueueReference[] queueReferences, string owner, string computerName)
        {
            return base.Channel.GetProcessedJobs(queueReferences, owner, computerName);
        }
        
        public SealSignSQSService.Job GetJob(int id)
        {
            return base.Channel.GetJob(id);
        }
        
        public SealSignSQSService.BiometricSignatureContext BeginBiometricSignatureProvider(int idDocument, int signatureIndex, string queueName, string biometricId, string biometricAccount, string uri, string providerParameter, byte[] document)
        {
            return base.Channel.BeginBiometricSignatureProvider(idDocument, signatureIndex, queueName, biometricId, biometricAccount, uri, providerParameter, document);
        }
        
        public byte[] EndBiometricSignatureProvider(System.Guid instance, byte[] biometricState, int idDocument, int signatureIndex, string queueName, string uri, string providerParameter)
        {
            return base.Channel.EndBiometricSignatureProvider(instance, biometricState, idDocument, signatureIndex, queueName, uri, providerParameter);
        }
        
        public void SyncOfflineSignature(int idDocument, int signatureIndex, string queueName, string biometricId, string biometricAccount, string uri, string providerParameter, byte[] document, System.Guid instance, byte[] offlineBiometricState)
        {
            base.Channel.SyncOfflineSignature(idDocument, signatureIndex, queueName, biometricId, biometricAccount, uri, providerParameter, document, instance, offlineBiometricState);
        }
        
        public byte[] SyncOfflineSignatureToArray(int idDocument, int signatureIndex, string queueName, string biometricId, string biometricAccount, string uri, string providerParameter, byte[] document, System.Guid instance, byte[] offlineBiometricState)
        {
            return base.Channel.SyncOfflineSignatureToArray(idDocument, signatureIndex, queueName, biometricId, biometricAccount, uri, providerParameter, document, instance, offlineBiometricState);
        }
        
        public void SyncOfflineSignatures(int idDocument, string queueName, SealSignSQSService.OfflineBiometricSignature[] offlineSignatures, byte[] document)
        {
            base.Channel.SyncOfflineSignatures(idDocument, queueName, offlineSignatures, document);
        }
        
        public byte[] SyncOfflineSignaturesToArray(int idDocument, string queueName, SealSignSQSService.OfflineBiometricSignature[] offlineSignatures, byte[] document)
        {
            return base.Channel.SyncOfflineSignaturesToArray(idDocument, queueName, offlineSignatures, document);
        }
    }
}
